name: Automated Tests

on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: CI
        run: npm ci

      - name: Tests
        run: npm run lint:Prettier:check

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: CI
        run: npm ci

      - name: Tests
        run: npm run lint:Eslint:check

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: CI
        run: npm ci

      - name: Commitlint
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~{{ commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
