name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Node installation
        uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"

      - name: CI
        run: npm ci

      - name: Tests
        run: npm test